import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon Api</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Simple <a href="https://pokeapivini.herokuapp.com/api/poke">Web Vitals</a> API
        </h1>

        <p className={styles.description}>
          Confira nossa documentação através da rota{' '}
          <code className={styles.code}>/api/documentation</code><br></br><br></br>
          ou as informações dos desenvolvedores em{' '}
          <code className={styles.code}>/api/dev</code>
        </p>
        

        <div className={styles.grid}>
          <a href="https://github.com/henquesz" className={styles.card}>
            <h2>GitHub &rarr;</h2>
            <p>Acesse o GitHub do dev responsável.</p>
          </a>

          <a href="https://www.linkedin.com/in/vinicius-henques-5a843a1b9/" className={styles.card}>
            <h2>LinkedIn &rarr;</h2>
            <p>Veja o perfil profissional do nosso dev.</p>
          </a>

          <a
            href="https://viniciushenquesportfolio.vercel.app"
            className={styles.card}
          >
            <h2>Portfólio &rarr;</h2>
            <p>Descubra projetos e todas as skills do nosso dev.</p>
          </a>

          <a
            href="https://github.com/henquesz/PokeApi"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Application &rarr;</h2>
            <p>
              Acesse o link de uso da nossa aplicação.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
